### ISSUE TITLE
remove political bullshit

### ISSUE THREAD

**Issue by idc77** [kyoto-framework/kyoto#117]
politics have no place in code. remove nazi slogan.

**Comment by yuriizinets** [comment]
First of all, please, check actual definition of “nazi”. Political situation in the Russia better fits this definition.
Second thing, I have a moral right to keep this. So much people lost their homes, relatives, friends. I’m spending a lot of time to help people who had to leave country and was lucky enough to stay alive.
Third thing, it called «Freedom of speech». Something you don’t know and not available in the Russia, unfortunately. I’m free to say whatever I want and do whatever I want. You don’t like this? Feel free to make own fork and go away from this thread.
