### ISSUE TITLE
Decoding a Base64-encoded component state

### ISSUE THREAD

**Issue by RowdyHcs** [kyoto-framework/kyoto#124]
**Describe the bug**
Sometimes, for some reason, component fields result in "-" in the component's state. What provokes atob failure and leads to at least broken actions

**To Reproduce**
UIkit -> TWUI -> AppUINavSidebar
Field:
```
Logo: template.HTML(`<a href="#">
			<img src="https://raw.githubusercontent.com/kyoto-framework/kyoto/master/.docs/.vuepress/public/kyoto.svg" class="mx-auto h-16 w-16 scale-150" />
		</a>`),
```

**Expected behavior**
Escaping before atob resulting in correct behavior where the component's fields do not affect the operation of the component

**Screenshots**
![atob](https://user-images.githubusercontent.com/31806782/163561398-a6570d1b-17af-4289-a5ea-1a7689c5ffb7.jpg)

**Comment by yuriizinets** [comment]
Replacing "-" to "/" missed before doing `atob`.
We can remove replacing "/" to "-" instead of hacking with replacements.
