### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by gedw99** [kyoto-framework/kyoto#134]
I guess that the i18n functions will be exposed in zen.

In zen you have string formatting for DateTime and maybe Currency, and so it seems to make sense to also have the i18n aspect there too ?  SO then you can do a template where you can say " Mr Kane made 2 apples on April 20th, 2019" in any language".

**Comment by yuriizinets** [comment]
Moved to https://github.com/kyoto-framework/i18n/issues/2
