### ISSUE TITLE
Concept: Detailed documentation for Actions

### ISSUE THREAD

**Issue by yuriizinets** [kyoto-framework/kyoto#137]

**Comment by ss185994** [comment]
👀

**Comment by yuriizinets** [comment]
@ss185994 
We are rethinking overall implementation concept, but with the same idea. You can see that in the "concept" branch now (it's better to start from doc.go, but it's not completed yet). IMO it's better to make such changes before 1.0 release, because from 1.0 we need to provide stable API. Just created some tasks with Concept prefix for Viktor and self-tracking. :) 
We are going to simplify architecture (80% of overall project's code is not actually needed), optimize overall development process (f.e. use in-code documentation with auto-generated pkg.go.dev, instead of own hosted), etc.
