### ISSUE TITLE
Documentation is restricted due to cache

### ISSUE THREAD

**Issue by yuriizinets** [kyoto-framework/kyoto#145]
`pkg.go.dev` cached v1.0.0 without a LICENSE file. After pushing license and force change tag commit, `pkg.go.dev` is not updating own cache.

**Comment by tgulacsi** [comment]
As I've experienced, It's easier to push the fix with a a bigger version number (v1.0.1) than force-push the wrong (v1.0.0) one.
It's annoying, but can be understood: a pushed version can be "cached" (pulled, downloaded) by a user of the library, and it's more straightforward to push a fix in a ... fix - (v1.0.1).
