### ISSUE TITLE
Can template.ParseGlob parse templates in subdirectories?

### ISSUE THREAD

**Issue by BenCherif** [kyoto-framework/kyoto#151]
Hi thanks for such great framework like this .
Can we parse templates in subdirectories which means we have /templates/ directory and subdirectories like 
- templates/components or templates/components/blog.
is there a function to  do this with your framework .
Kind regards

**Comment by yuriizinets** [comment]
Hi, Ben!
Sorry to say, there is no way now to provide glob with ** semantics.
Probably you'll want to check this: https://stackoverflow.com/questions/32309830/can-template-parseglob-parse-templates-in-subdirectories

Now you have 3 options to choose from:
- Stick with a flat structure.
- Stick with a constant nesting number, like `templates/*/*/*.html` for `templates/components/blog/file.html`.
- Provide your own prepared template with `kyoto.TemplateRaw`. Anyway, it doesn't provide you with a solution, rather it allows you to integrate your own.

I'm not going to push for any specific option, feel free to evaluate pros/cons for your exact case :)

Kind Regards,
Yurii

**Comment by BenCherif** [comment]
Thans  Yurri i appreciate your help , i will try your suggestions .
maybe i will try to find a solution soon .
Kind regards

**Comment by BenCherif** [comment]
Thanks for your suggestion i've find a way to make this work .
