### ISSUE TITLE
Abandoned? 

### ISSUE THREAD

**Issue by ZueffC** [kyoto-framework/kyoto#157]
Is this project dead?

**Comment by yuriizinets** [comment]
Nope, but still needs more attention from me :)
There is a work on v3 (in the corresponding branch), which is not merged into master yet.

I can't track real usage of the library and how many people rely on it.
I know at most 2-3 real use cases (excluding my owns). If you're relying on the library, please, let me know.

Not so long ago people started sponsoring, so I'm gonna to spend a bit more time on the lib.
