### ISSUE TITLE
Transaction not going through

### ISSUE THREAD

**Issue by Kunzopapi** [kyoto-framework/kyoto#166]
<img width="597" alt="Screenshot 2024-02-21 at 15 42 00" src="https://github.com/kyoto-framework/kyoto/assets/39674554/ab88f1b7-9c29-4ad5-9dc4-cc41a7bc7cf4">
trying to delpy contraction but the transaction has been stocked for over 2 days

**Comment by yuriizinets** [comment]
I don't think this message belongs here
