### ISSUE TITLE
Nested components directories

### ISSUE THREAD

**Issue by BenCherif** [kyoto-framework/kyoto#169]
Hi ,
i've use the v2 of this framework and i've faced an issue of. nested html directories after a while i found a solution :
<img width="248" alt="image" src="https://github.com/user-attachments/assets/eded8d95-336e-4a5c-abae-5428be304b3c">
this the result i achieve .But now with the v3 i can't find a. solution for this issue if you have any insights don't hesitate to tell us .

Kind regards

**Comment by yznts** [comment]
You're able to do that at least in 2 ways:
- You can set a custom settings per page, like `state.Template.Glob = ...`. Feel free to change whatever you want in Template configuration: https://github.com/kyoto-framework/kyoto/blob/069f55a1676bc306b37a2c4a5f461efb7b0c4ed1/rendering/renderer.template.go#L22
- You can set a global settings for the whole module. Example from my project: https://github.com/yznts/oxigen/blob/62e58bee81290718a3d700b52bcbf6b9ef76a3a9/main.go#L24

**Comment by BenCherif** [comment]
@yznts  Thanks  i will check it
