### ISSUE TITLE
Server Side State

### ISSUE THREAD

**Issue by yuriizinets** [kyoto-framework/kyoto#28]
Will be useful in case of large state payloads.  
Instead of saving state inline as html tag, store state on server side and inject state hash as html tag.  
This feature will decrease amount of data, sent with SSA request and total HTML document size.

Key requirements:  
- Implement at least in-memory storage
- Support for multiple state storages (with interface)
- Component-level storage configuration (inline or server-side)

**Comment by yuriizinets** [comment]
Moving to 0.3, not covered by 0.2 features focus group

**Comment by gedw99** [comment]
I am not that familiar with kyoto yet but see interfaces used for the Actions in the demo code.

do you think a more formalised data structure for this is needed ? 
Protobufs can be really nice for this where you want to define a structure. 

I was thinking a simple KV structure that is tagged / nested based on a simple namespace.
SO each component has a namespace and then can put whatever it wants.

This is a decent example of the concept: https://github.com/simpleiot/simpleiot/blob/master/internal/pb/node.proto

You can use protobufs over SSE btw.  Its just a serialisation.
