### ISSUE TITLE
Support newline delimited JSON output for insights

### ISSUE THREAD

**Issue by yuriizinets** [kyoto-framework/kyoto#49]
Add `INSIGHTS_CLI_JSON` config to support output in JSON format

**Comment by inthepanchine** [comment]
Should the output be indented?

**Comment by yuriizinets** [comment]
No, it's enough to print everything inline, like `{"i":0,"a":0,"aa":0, ...}`
Main idea of newline delimited JSON is to analyze this output with external tools.
