### ISSUE TITLE
Review documentation for grammar mistakes

### ISSUE THREAD

**Issue by yuriizinets** [kyoto-framework/kyoto#79]

**Comment by OpenSauce** [comment]
I can pick this up - any areas in particular that need going over?

**Comment by yuriizinets** [comment]
"Extended Features" category was updated, especially "Server Side Actions".
https://kyoto.codes/extended-features/server-side-actions/

As well as "Getting started". 
https://kyoto.codes/getting-started/

I'll be very glad! My English is far away from acceptable and this is especially critical for things like documentation 😄
