### ISSUE TITLE
Support `tinygo` compiler

### ISSUE THREAD

**Issue by yuriizinets** [kyoto-framework/kyoto#80]
`tinygo` may provide a lot of benefits to the project, like compiling to smaller `wasm` payload and using in places where payload size is critical. I also consider as an option using `kyoto` for creating frontend, rendered on the Edge Network (f.e. Cloudflare Workers). Workers have a lot of limitations and `tinygo` may satisfy them.

**Comment by gedw99** [comment]
Its wy smaller. I go from 1 MB to 30 KB with it.

The main thing is to get rid of reflection.  github.com/buger/jsonparser

Example to prove it :)

https://github.com/genjidb/genji is a DB that can run Server side and client side. Its like MongoDB but in golang. 

You can compile it using tinygo.
https://github.com/genjidb/genji.js/blob/master/scripts/buildgo.sh#L27

**Comment by yuriizinets** [comment]
Seems to be no reasonable solution for this.

- Library highly depends on templating, which relies on reflection, which is badly supported by tinygo
- Library also relies on goroutines, synchronization techniques, etc, which also pretty different in tinygo

Initially main idea was to use kyoto in Cloudflare Workers. But the "price" of the solution and refactor is much higher than the potential profit.

**Comment by gedw99** [comment]
I get your point about the pain 

there are other golang template engines that don’t use reflection i think.

the go routines might still work in tinygo. I remember reading sone progress on this in tinygo recently . Can fin link right now.
